root: true
env:
  browser: true
  node: true
  es6: true

parserOptions:
  sourceType: module
  ecmaVersion: 2020
  extraFileExtensions: ['.svelte']

extends:
  - standard
  - eslint:recommended
  - plugin:import/warnings
  - plugin:jest/recommended
  - plugin:svelte/recommended
  - prettier

plugins:
  - jest

rules:
  arrow-parens: [2, always]
  indent: [error, 4]
  linebreak-style: [error, unix]
  semi: [error, always]
  quotes: [error, "double"]
  array-callback-return: [error]
  no-useless-concat: [error]
  space-before-function-paren: [error, never]

ignorePatterns:
  - vite.config.js
