# This file override .editorconfig
plugins = [
    "prettier-plugin-svelte"
]
trailingComma = "none"
svelteSortOrder = "options-scripts-markup-styles"
svelteAllowShorthand = true
bracketSameLine = false
svelteIndentScriptAndStyle = true
htmlWhitespaceSensitivity = "ignore"
