version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  web:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:3000
    environment:
      PORTGRES_URI: postgres://postgres:password@postgres/postgres
      # Used by graphile-migrate
      DATABASE_URL: postgres://postgres:password@postgres/postgres
    depends_on:
      postgres:
        condition: service_healthy

